name: Deploy to Google App Engine

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'run.sh'
      - 'Dockerfile'
      - 'app.yml'

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy --quiet --promote